# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bspline <- function(x, l, r) {
    .Call(`_contdid_bspline`, x, l, r)
}

jhat <- function(PP, BB, CJ, CK, TJ, M, n, nL) {
    .Call(`_contdid_jhat`, PP, BB, CJ, CK, TJ, M, n, nL)
}

jlep <- function(Lhat, Px, PP, BB, CJ, CK, TJ, y, n, nb) {
    .Call(`_contdid_jlep`, Lhat, Px, PP, BB, CJ, CK, TJ, y, n, nb)
}

npiv <- function(P, B, y) {
    .Call(`_contdid_npiv`, P, B, y)
}

npiv_estimate_cpp <- function(Ltil, Px, PP, BB, CJ, CK, y, n) {
    .Call(`_contdid_npiv_estimate_cpp`, Ltil, Px, PP, BB, CJ, CK, y, n)
}

shat <- function(P, B) {
    .Call(`_contdid_shat`, P, B)
}

