name: R Package Checks

on:
  push:
    branches: [main, master, develop, dev]
  pull_request:
    branches: [main, master, develop, dev]
  workflow_dispatch:

jobs:
  determine_check_type:
    runs-on: ubuntu-latest
    outputs:
      run_type: ${{ steps.check_run_type.outputs.run_type }}
    steps:
      - uses: actions/checkout@v4
      - id: check_run_type
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[long-run]"* ]]; then
            echo "run_type=comprehensive" >> $GITHUB_OUTPUT
          else
            echo "run_type=quick" >> $GITHUB_OUTPUT
          fi

  test:
    needs: determine_check_type
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat, any::devtools, any::rcmdcheck
          needs: check
      - name: Run quick check
        if: needs.determine_check_type.outputs.run_type == 'quick'
        run: |
          options(crayon.enabled = TRUE)
          devtools::load_all()
          testthat::test_dir("tests/testthat", reporter = "summary")
        shell: Rscript {0}
      - name: Run comprehensive check
        if: needs.determine_check_type.outputs.run_type == 'comprehensive'
        env:
          R_CHECK_CRAN_INCOMING: false
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
      - name: Run tests (comprehensive)
        if: needs.determine_check_type.outputs.run_type == 'comprehensive'
        run: |
          options(crayon.enabled = TRUE)
          devtools::load_all()
          test_results <- testthat::test_dir("tests/testthat", reporter = "summary")
          saveRDS(test_results, file = "test_results.rds")
          print(test_results)
        shell: Rscript {0}
      - name: Upload check results
        if: failure() && needs.determine_check_type.outputs.run_type == 'comprehensive'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: needs.determine_check_type.outputs.run_type == 'comprehensive'
        with:
          name: test-results-${{ matrix.config.os }}
          path: |
            test_results.rds
            tests/testthat/
