name: R Package Checks

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat, any::devtools
          needs: check

      - name: Check package structure
        run: |
          pwd
          ls -R
        shell: bash

      - name: Run tests with devtools
        run: |
          Rscript -e '
          library(devtools)
          library(testthat)
          setwd(getwd())
          devtools::load_all()
          test_results <- tryCatch(
            devtools::test(),
            error = function(e) {
              message("Error occurred: ", e$message)
              return(NULL)
            }
          )
          if (is.null(test_results)) {
            quit(status = 1)
          }
          '
        shell: bash

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: tests/testthat/
